language: r
before_install:
        - sudo apt-get update
        - sudo apt-get -y install libssl-dev python3-mpi4py libcurl4-openssl-dev libxml2-dev
install: Rscript travis/inst.R

# we build a (1d)matrix of testsuites
env:
        - TEST_SUITE=./travis_check_pkg.sh
        - TEST_SUITE=./travis_run_all_tests.sh
        - TEST_SUITE=./travis_install_SoilR_from_src.sh
# run the matrix
script:  
        - "$TEST_SUITE" 

notifications:
  email:
    recipients:
      - mamueller@bgc-jena.mpg.de
      - markus.mueller.1.g@googlemail.com
      - hmetzler@bgc-jena.mpg.de
      - csierra@bgc-jena.mpg.de
      - vceball@bgc-jena.mpg.de
    on_success: change # default: change
    on_failure: always # default: always
