language: r
before_install:
        - sudo apt-get update
        - sudo apt-get -y install libssl-dev python3-mpi4py libcurl4-openssl-dev libxml2-dev ghostscript
install: Rscript travis/inst.R

# we build a (1d)matrix of testsuites
env:
        - TEST_SUITE="./scripts/check_rhub.R"
          #        - TEST_SUITE= "cd scripts; Rscript check_local.R"
          #        - TEST_SUITE= "cd pkg/inst/tests; Rscript all.R ;Rscript sall.R"
          #        - TEST_SUITE= "cd pkg/inst/tests; Rscript inst.R"
# run the matrix
# we use bash eval
script:  bash "$TEST_SUITE" 

notifications:
  email:
    recipients:
      - mamueller@bgc-jena.mpg.de
      - markus.mueller.1.g@googlemail.com
      - hmetzler@bgc-jena.mpg.de
      - csierra@bgc-jena.mpg.de
      - vceball@bgc-jena.mpg.de
    on_success: change # default: change
    on_failure: always # default: always
