language: r
before_install:
        - sudo apt-get update
        - sudo apt-get -y install libssl-dev python3-mpi4py libcurl4-openssl-dev libxml2-dev
install: Rscript travis/inst.R
script:  ./travis_run_all_tests.sh

notifications:
  email:
    recipients:
      - mamueller@bgc-jena.mpg.de
      - markus.mueller.1.g@googlemail.com
      - hmetzler@bgc-jena.mpg.de
      - csierra@bgc-jena.mpg.de
      - vceball@bgc-jena.mpg.de
    on_success: change # default: change
    on_failure: always # default: always
